"""Modified foreign key in Blogs

Revision ID: 5147496d4195
Revises: 3576d78679ae
Create Date: 2023-07-18 21:17:12.234261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5147496d4195'
down_revision = '3576d78679ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
